// Sample hostel data + constants for NestStay
const HOSTEL_TYPES = [
  { id: 'all', label: 'All' },
  { id: 'student', label: 'Student' },
  { id: 'women', label: "Women's" },
  { id: 'mess', label: 'Bachelor Mess' },
  { id: 'corporate', label: 'Corporate' },
  { id: 'worker', label: "Worker's" },
  { id: 'medical', label: 'Medical' },
];

const TYPE_PILL_COLOR = {
  student: 'pill-purple',
  women: 'pill-pink',
  mess: 'pill-blue',
  corporate: 'pill-teal',
  worker: 'pill-amber',
  medical: 'pill-coral',
};

const AMENITIES = [
  { id: 'wifi', label: 'WiFi', icon: 'Wifi' },
  { id: 'meal', label: 'Meal included', icon: 'Utensils' },
  { id: 'ac', label: 'AC', icon: 'Snowflake' },
  { id: 'gen', label: 'Generator', icon: 'Zap' },
  { id: 'cctv', label: 'CCTV', icon: 'Camera' },
  { id: 'study', label: 'Study room', icon: 'Book' },
  { id: 'laundry', label: 'Laundry', icon: 'Shirt' },
  { id: 'bath', label: 'Attached bath', icon: 'Droplet' },
  { id: 'hot', label: 'Hot water', icon: 'Droplet' },
  { id: 'guard', label: '24h guard', icon: 'Shield' },
  { id: 'prayer', label: 'Prayer room', icon: 'Home' },
  { id: 'locker', label: 'Locker', icon: 'Lock' },
  { id: 'bike', label: 'Bike parking', icon: 'Bike' },
  { id: 'rooftop', label: 'Rooftop', icon: 'Mountain' },
  { id: 'canteen', label: 'Canteen', icon: 'Coffee' },
];

// 6 gradient palettes used for placeholder photos
const PHOTO_GRADS = [
  'linear-gradient(135deg, #1A6B72 0%, #34A6A6 100%)',
  'linear-gradient(135deg, #FF8E8E 0%, #FF6B6B 60%, #C94F65 100%)',
  'linear-gradient(135deg, #6B47C0 0%, #9377DC 100%)',
  'linear-gradient(135deg, #1D6FD1 0%, #5BA0E8 100%)',
  'linear-gradient(135deg, #A65800 0%, #FF9500 100%)',
  'linear-gradient(135deg, #1E8C3F 0%, #34C759 100%)',
  'linear-gradient(135deg, #0E484D 0%, #1A6B72 50%, #FF6B6B 130%)',
  'linear-gradient(135deg, #B53D7C 0%, #FF8E8E 100%)',
];

const HOSTELS = [
  {
    id: 'asha',
    name: "Asha Women's Hostel",
    type: 'women',
    typeLabel: "Women's",
    gender: 'female',
    location: 'Mirpur 1, Dhaka',
    landmark: 'near BUET',
    landmarkDist: '0.8km from BUET',
    rating: 4.8,
    reviews: 124,
    seats: { total: 20, vacant: 5 },
    price: 4500,
    priceUnit: 'seat/month',
    advance: 2000,
    meal: { included: true, price: 1500 },
    curfew: '10:00 PM',
    verified: true,
    grad: PHOTO_GRADS[1],
    owner: { name: 'Asha Begum', phone: '01XXXXXXXXX' },
    description: "A safe, well-managed women's hostel located in the heart of Mirpur 1. Just a short walk to BUET, with 24-hour security, attached bath in every room, and home-cooked meals served three times a day. Curfew enforced at 10 PM.",
    amenities: ['wifi', 'meal', 'cctv', 'study', 'laundry', 'bath', 'hot', 'guard', 'prayer', 'locker'],
    rules: [
      'Curfew: 10:00 PM every night',
      'No male visitors above floor 1',
      'No cooking in rooms',
      'Noise curfew after 11 PM',
      'Advance: 1 month seat rent',
      'Notice period: 15 days before vacating',
    ],
    floor: '3rd floor',
    building: 'Apartment',
    rooms: [
      { name: 'Room 1', seats: [
        { id: 'R1-A', status: 'taken' }, { id: 'R1-B', status: 'taken' },
        { id: 'R1-C', status: 'vacant' }, { id: 'R1-D', status: 'reserved' },
        { id: 'R1-E', status: 'vacant' }, { id: 'R1-F', status: 'taken' },
      ]},
      { name: 'Room 2', seats: [
        { id: 'R2-A', status: 'taken' }, { id: 'R2-B', status: 'vacant' },
        { id: 'R2-C', status: 'taken' }, { id: 'R2-D', status: 'taken' },
        { id: 'R2-E', status: 'vacant' }, { id: 'R2-F', status: 'taken' },
      ]},
      { name: 'Room 3', seats: [
        { id: 'R3-A', status: 'taken' }, { id: 'R3-B', status: 'taken' },
        { id: 'R3-C', status: 'vacant' }, { id: 'R3-D', status: 'taken' },
        { id: 'R3-E', status: 'taken' }, { id: 'R3-F', status: 'reserved' },
      ]},
    ],
    reviewsList: [
      { name: 'Tahmina Akter', date: 'Apr 2026', rating: 5, body: 'Very clean and the meals are home-style. Security is strict which I appreciate. Stayed for 8 months and felt safe.' },
      { name: 'Nusrat J.', date: 'Mar 2026', rating: 5, body: 'Great location, walk to BUET in 10 minutes. Asha apa is very caring. Wifi could be faster though.' },
      { name: 'Sumaiya R.', date: 'Feb 2026', rating: 4, body: 'Good value for the price. Curfew is a bit early but understandable for safety.' },
    ],
  },
  {
    id: 'green',
    name: 'Green Valley Mess',
    type: 'mess', typeLabel: 'Bachelor Mess',
    gender: 'male',
    location: 'Dhanmondi 15', landmark: 'Dhaka', landmarkDist: '1.5km from Dhanmondi Lake',
    rating: 4.5, reviews: 86,
    seats: { total: 12, vacant: 2 },
    price: 3800, priceUnit: 'seat/month', advance: 3800,
    meal: { included: false, price: 0 },
    curfew: null,
    verified: false,
    grad: PHOTO_GRADS[0],
    owner: { name: 'Rafiq Hossain', phone: '01XXXXXXXXX' },
    description: 'Bachelor mess in central Dhanmondi. Spacious rooms, no meal service (kitchen access provided), great location for working professionals.',
    amenities: ['wifi', 'cctv', 'laundry', 'bath', 'hot', 'guard'],
    rules: ['No female visitors', 'No smoking indoors', 'Quiet hours after 11 PM', 'Advance: 1 month rent', 'Notice period: 30 days'],
    floor: '2nd floor', building: 'Apartment',
    rooms: [
      { name: 'Room 1', seats: [{id:'R1-A',status:'taken'},{id:'R1-B',status:'taken'},{id:'R1-C',status:'taken'},{id:'R1-D',status:'vacant'}]},
      { name: 'Room 2', seats: [{id:'R2-A',status:'taken'},{id:'R2-B',status:'taken'},{id:'R2-C',status:'taken'},{id:'R2-D',status:'vacant'}]},
      { name: 'Room 3', seats: [{id:'R3-A',status:'taken'},{id:'R3-B',status:'taken'},{id:'R3-C',status:'taken'},{id:'R3-D',status:'taken'}]},
    ],
    reviewsList: [
      { name: 'Imran Hossain', date: 'Apr 2026', rating: 4, body: 'Decent place for working bachelors. Kitchen is shared but clean.' },
      { name: 'Saiful K.', date: 'Mar 2026', rating: 5, body: 'Owner is responsive. Wifi is solid. No meal service so flexibility is nice.' },
      { name: 'Mahbub A.', date: 'Jan 2026', rating: 4, body: 'Central location, easy commute. Could use better laundry.' },
    ],
  },
  {
    id: 'meghna',
    name: 'Meghna Student Home',
    type: 'student', typeLabel: 'Student',
    gender: 'mixed',
    location: 'Rajshahi', landmark: 'near Rajshahi University', landmarkDist: '600m from RU campus',
    rating: 4.7, reviews: 92,
    seats: { total: 30, vacant: 8 },
    price: 2800, priceUnit: 'seat/month', advance: 2800,
    meal: { included: true, price: 1200 },
    curfew: '11:00 PM',
    verified: true,
    grad: PHOTO_GRADS[2],
    owner: { name: 'Dr. Karim Uddin', phone: '01XXXXXXXXX' },
    description: 'Student-friendly hostel close to Rajshahi University campus. Mixed gender (separate floors). Quiet study environment, dedicated study room, three meals per day included for ৳1,200/month.',
    amenities: ['wifi', 'meal', 'study', 'cctv', 'laundry', 'guard', 'prayer', 'canteen'],
    rules: ['Floors are gender-separated', 'Curfew 11 PM', 'Visitors only in common area', 'Advance: 1 month rent', 'Notice: 15 days'],
    floor: 'Full building', building: 'Independent building',
    rooms: [
      { name: 'Room 1', seats: [{id:'R1-A',status:'taken'},{id:'R1-B',status:'vacant'},{id:'R1-C',status:'taken'},{id:'R1-D',status:'taken'},{id:'R1-E',status:'vacant'},{id:'R1-F',status:'taken'}]},
      { name: 'Room 2', seats: [{id:'R2-A',status:'vacant'},{id:'R2-B',status:'taken'},{id:'R2-C',status:'vacant'},{id:'R2-D',status:'taken'},{id:'R2-E',status:'taken'},{id:'R2-F',status:'reserved'}]},
      { name: 'Room 3', seats: [{id:'R3-A',status:'taken'},{id:'R3-B',status:'taken'},{id:'R3-C',status:'vacant'},{id:'R3-D',status:'vacant'},{id:'R3-E',status:'taken'},{id:'R3-F',status:'taken'}]},
    ],
    reviewsList: [
      { name: 'Rifat H.', date: 'Apr 2026', rating: 5, body: 'Best part is the study room — open 24/7. Great for finals.' },
      { name: 'Anika S.', date: 'Mar 2026', rating: 5, body: 'Food is good, hostel is clean. Walking distance to campus.' },
      { name: 'Sajid M.', date: 'Feb 2026', rating: 4, body: 'Affordable and well-maintained. Wifi drops occasionally.' },
    ],
  },
  {
    id: 'capital',
    name: 'Capital Guesthouse',
    type: 'corporate', typeLabel: 'Corporate',
    gender: 'mixed',
    location: 'Motijheel', landmark: 'Dhaka CBD', landmarkDist: '5min walk to Motijheel station',
    rating: 4.3, reviews: 41,
    seats: { total: 10, vacant: 3 },
    price: 1200, priceUnit: 'day', advance: 1200,
    meal: { included: false, price: 0 },
    curfew: null,
    verified: false,
    grad: PHOTO_GRADS[3],
    owner: { name: 'Capital Hospitality Ltd.', phone: '01XXXXXXXXX' },
    description: 'Corporate guesthouse in Motijheel for short-stay business travelers. Per-day pricing, daily housekeeping, breakfast available.',
    amenities: ['wifi', 'ac', 'cctv', 'laundry', 'bath', 'hot', 'guard'],
    rules: ['ID required at check-in', 'No outside visitors after 9 PM', 'Per-day billing', 'Check-out by 12 PM'],
    floor: '4th & 5th floor', building: 'Commercial tower',
    rooms: [
      { name: 'Room 1', seats: [{id:'R1-A',status:'taken'},{id:'R1-B',status:'taken'},{id:'R1-C',status:'vacant'},{id:'R1-D',status:'taken'}]},
      { name: 'Room 2', seats: [{id:'R2-A',status:'vacant'},{id:'R2-B',status:'taken'},{id:'R2-C',status:'vacant'},{id:'R2-D',status:'taken'}]},
    ],
    reviewsList: [
      { name: 'Tareq A.', date: 'Apr 2026', rating: 4, body: 'Convenient for short business trips. Clean rooms.' },
      { name: 'Ms. Farzana', date: 'Mar 2026', rating: 4, body: 'AC works well, staff is professional.' },
      { name: 'Habib R.', date: 'Feb 2026', rating: 5, body: 'Best location in Motijheel. Slightly pricey per night but worth it.' },
    ],
  },
  {
    id: 'padma',
    name: "Padma Worker's Dorm",
    type: 'worker', typeLabel: "Worker's",
    gender: 'male',
    location: 'Ashulia EPZ', landmark: 'Savar', landmarkDist: '300m from EPZ Gate 2',
    rating: 4.4, reviews: 168,
    seats: { total: 50, vacant: 14 },
    price: 2500, priceUnit: 'seat/month', advance: 2500,
    meal: { included: true, price: 1000 },
    curfew: '10:30 PM',
    verified: false,
    grad: PHOTO_GRADS[4],
    owner: { name: 'Padma Dormitory Co.', phone: '01XXXXXXXXX' },
    description: 'Large dormitory for EPZ workers. Bunk beds, three shifts, meal canteen on-site, prayer room, lockers for each worker.',
    amenities: ['meal', 'cctv', 'guard', 'prayer', 'locker', 'canteen', 'laundry'],
    rules: ['ID badge required', 'Curfew 10:30 PM', 'Quiet hours during shift sleep', 'Advance: 1 month rent', 'Notice: 7 days'],
    floor: 'Ground + 2 floors', building: 'Purpose-built dorm',
    rooms: [
      { name: 'Bay A', seats: [{id:'A-1',status:'taken'},{id:'A-2',status:'taken'},{id:'A-3',status:'vacant'},{id:'A-4',status:'taken'},{id:'A-5',status:'vacant'},{id:'A-6',status:'taken'}]},
      { name: 'Bay B', seats: [{id:'B-1',status:'vacant'},{id:'B-2',status:'taken'},{id:'B-3',status:'vacant'},{id:'B-4',status:'vacant'},{id:'B-5',status:'taken'},{id:'B-6',status:'vacant'}]},
      { name: 'Bay C', seats: [{id:'C-1',status:'taken'},{id:'C-2',status:'taken'},{id:'C-3',status:'vacant'},{id:'C-4',status:'taken'},{id:'C-5',status:'taken'},{id:'C-6',status:'reserved'}]},
    ],
    reviewsList: [
      { name: 'Jamal M.', date: 'Apr 2026', rating: 4, body: "Affordable and right next to EPZ. Canteen food is okay." },
      { name: 'Rakib H.', date: 'Mar 2026', rating: 5, body: 'Great for night shift workers. Lockers are useful.' },
      { name: 'Sumon A.', date: 'Feb 2026', rating: 4, body: 'Crowded but clean. Owner is reachable.' },
    ],
  },
  {
    id: 'comfort',
    name: 'Comfort Care Hostel',
    type: 'medical', typeLabel: 'Medical',
    gender: 'mixed',
    location: 'Shahbag', landmark: 'near DMCH', landmarkDist: '200m from DMCH main gate',
    rating: 4.6, reviews: 67,
    seats: { total: 8, vacant: 2 },
    price: 900, priceUnit: 'day', advance: 900,
    meal: { included: true, price: 800 },
    curfew: null,
    verified: true,
    grad: PHOTO_GRADS[5],
    owner: { name: 'Comfort Care Ltd.', phone: '01XXXXXXXXX' },
    description: 'Hostel for patient attendants near Dhaka Medical College Hospital. Per-day stays, light meals available, 24/7 access, attached bath.',
    amenities: ['wifi', 'meal', 'ac', 'cctv', 'bath', 'hot', 'guard'],
    rules: ['Patient attendant ID encouraged', 'No curfew', 'Quiet hours after 10 PM', 'Per-day billing', 'Advance: 1 day rent'],
    floor: '2nd floor', building: 'Apartment',
    rooms: [
      { name: 'Room 1', seats: [{id:'R1-A',status:'taken'},{id:'R1-B',status:'vacant'},{id:'R1-C',status:'taken'},{id:'R1-D',status:'taken'}]},
      { name: 'Room 2', seats: [{id:'R2-A',status:'taken'},{id:'R2-B',status:'taken'},{id:'R2-C',status:'vacant'},{id:'R2-D',status:'taken'}]},
    ],
    reviewsList: [
      { name: 'Mr. Anwar', date: 'Apr 2026', rating: 5, body: 'A lifesaver when my mother was admitted at DMCH. Walked over in 3 minutes.' },
      { name: 'Mrs. Selina', date: 'Mar 2026', rating: 4, body: 'Clean and very close to the hospital. AC works well.' },
      { name: 'Mohid K.', date: 'Feb 2026', rating: 5, body: 'Staff understood our situation, very accommodating.' },
    ],
  },
];

const DIVISIONS = ['Dhaka', 'Chittagong', 'Rajshahi', 'Khulna', 'Sylhet', 'Barishal', 'Rangpur', 'Mymensingh'];
const DISTRICTS = {
  Dhaka: ['Dhaka', 'Gazipur', 'Narayanganj', 'Tangail', 'Manikganj', 'Munshiganj'],
  Chittagong: ['Chittagong', "Cox's Bazar", 'Comilla', 'Feni', 'Noakhali'],
  Rajshahi: ['Rajshahi', 'Bogura', 'Pabna', 'Sirajganj', 'Natore'],
  Khulna: ['Khulna', 'Jessore', 'Satkhira', 'Bagerhat'],
  Sylhet: ['Sylhet', 'Sunamganj', 'Habiganj', 'Moulvibazar'],
  Barishal: ['Barishal', 'Patuakhali', 'Pirojpur'],
  Rangpur: ['Rangpur', 'Dinajpur', 'Nilphamari'],
  Mymensingh: ['Mymensingh', 'Jamalpur', 'Sherpur', 'Netrokona'],
};
const UPAZILAS = {
  Dhaka: ['Mirpur', 'Dhanmondi', 'Motijheel', 'Gulshan', 'Mohammadpur', 'Uttara'],
  Rajshahi: ['Boalia', 'Motihar', 'Shah Makhdum', 'Rajpara'],
};

const fmtBDT = (n) => '৳' + Number(n).toLocaleString('en-BD');

Object.assign(window, {
  HOSTELS, AMENITIES, HOSTEL_TYPES, TYPE_PILL_COLOR, PHOTO_GRADS,
  DIVISIONS, DISTRICTS, UPAZILAS, fmtBDT,
});
